### PR TITLE
Add option to accept messages without headers as non-backed

### PR DESCRIPTION
**Pull request by philipp94831**

### CODE REVIEW

**Review by torbsto — COMMENTED** [review]
So, I was a bit confused how those two configs interact and came up with the following table:
| `large.message.use.headers`   | `large.message.accept.no.headers`  | Read: Header found              | Read: Header not found                | Write             | 
|-------------------------------|------------------------------------|---------------------------------|---------------------------------------|---------------------------------|
| `true`                        | `true`                             | Information from header is used | Wrapped serializer is used            | Header is written               | 
| `true`                        | `false`                            | Information from header is used | Byte flag is used, error if not found | Header is written               | 
| `false`                       | `true`                             | Information from header is used | Wrapped serializer is used            | Byte flag is written            | 
| `false`                       | `false`                            | Information from header is used | Byte flag is used, error if not found | Byte flag is written |   

Essentially,  `large.message.use.headers`  configures how the serde **writes** records, while `large.message.accept.no.headers` configures how records **without the header are read**. Correct? Maybe we could add this idea to the docs.

**Comment by philipp94831** [comment]
> So, I was a bit confused how those two configs interact and came up with the following table:
> 
> `large.message.use.headers`	`large.message.accept.no.headers`	Read: Header found	Read: Header not found	Write
> `true`	`true`	Information from header is used	Wrapped serializer is used	Header is written
> `true`	`false`	Information from header is used	Byte flag is used, error if not found	Header is written
> `false`	`true`	Information from header is used	Wrapped serializer is used	Byte flag is written
> `false`	`false`	Information from header is used	Byte flag is used, error if not found	Byte flag is written
> Essentially, `large.message.use.headers` configures how the serde **writes** records, while `large.message.accept.no.headers` configures how records **without the header are read**. Correct? Maybe we could add this idea to the docs.

I don't know how the table helps because the last column only depends on `large.message.use.headers` and the penultimate column only depends on `large.message.accept.no.headers`

**Comment by torbsto** [comment]
The table doesn't help, I just wanted to make sure that my understanding is correct

**Comment by philipp94831** [comment]
> The table doesn't help, I just wanted to make sure that my understanding is correct

I think so. Writing only depends on `large.message.use.headers`. When reading, the following happens:
- Header found: use header
- Header not found:
  - If `large.message.accept.no.headers`: pretend there is a header saying that the message is not backed
  - Else: expect byte flag in message key/value

**Review by torbsto — APPROVED** [review]
I guess my confusion mostly stems from the fact that `large.message.use.headers` configures only the behavior for writes. This could be made more clear in its description, although it mostly an implementation detail

**Pull request merged**
